CREATE TABLE public."user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       TEXT                                     NOT NULL,
    email      TEXT                                     NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE public."user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

CREATE TABLE public.task
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    title      TEXT                                     NOT NULL,
    body       TEXT,
    status     BOOLEAN                                  NOT NULL DEFAULT FALSE,
    user_id    BIGINT                                   NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE public.task
    ADD CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES public."user" (id) ON DELETE CASCADE;

CREATE TABLE public.task_labels
(
    task_id BIGINT NOT NULL,
    label   TEXT,
    CONSTRAINT fk_task_labels_task FOREIGN KEY (task_id) REFERENCES public.task (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_email ON public."user" (email);
CREATE INDEX idx_task_user_id ON public.task (user_id);
CREATE INDEX idx_task_status ON public.task (status);
CREATE INDEX idx_task_labels_task_id ON public.task_labels (task_id);